name: base
channels:
  - defaults
dependencies:
  - conda
  - python=3.9
  - conda-env
  - conda-build
  - conda-verify
  - anaconda
  - anaconda-navigator
  - navigator-updater
  - libgcc
  - torchinfo
  - pytorch=1.12.1
  - torchvision=0.12.0
  - cudatoolkit=11.6
  - torchaudio=0.12.1
