name: base
channels:
  - defaults
dependencies:
  - conda
  - python=3.9
  - conda-env
  - conda-build
  - conda-verify
  - anaconda
  - anaconda-navigator
  - navigator-updater
  - libgcc
  - torchinfo
  - pytorch
  - torchvision
  - cudatoolkit=11.6
  - torchaudio
